spring:
  application:
    name: customers-integrator
  server:
    port: 8080
  datasource:
    url: jdbc:postgresql://localhost:5432/customersintegratordb
    username: postgres
    password: CI2020
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false